config/routes.rb
Episoder::Application.routes.draw do
  resources :generos

  resources :seriados do
    resources :temporadas
    collection do
      get :buscar
    end
  end
  
  root :to => 'seriados#index'
end

app/models/genero.rb
class Genero < ActiveRecord::Base
  attr_accessible :name
end

app/models/seriado.rb
class Seriado < ActiveRecord::Base
  attr_accessible :inicio, :nome, :status, :sinopse, :foto
  has_many :temporadas

  has_attached_file :foto, :styles => { :medium => "150x150>", :thumb => "50x50>" }, :default_url => "/images/:style/missing.png"  
  
  validates :nome, :presence => true
end

app/models/temporada.rb
class Temporada < ActiveRecord::Base
  attr_accessible :numero, :seriado_id, :sinopse, :titulo

  belongs_to :seriado
  has_many :episodios
  
  validates :numero, :seriado_id, :presence => true
  validates :seriado_id, :numericality => { :only_integer => true, :greater_than => 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  # GET /generos
  # GET /generos.json
  def index
    @generos = Genero.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @generos }
    end
  end

  # GET /generos/1
  # GET /generos/1.json
  def show
    @genero = Genero.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @genero }
    end
  end

  # GET /generos/new
  # GET /generos/new.json
  def new
    @genero = Genero.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @genero }
    end
  end

  # GET /generos/1/edit
  def edit
    @genero = Genero.find(params[:id])
  end

  # POST /generos
  # POST /generos.json
  def create
    @genero = Genero.new(params[:genero])

    respond_to do |format|
      if @genero.save
        format.html { redirect_to @genero, notice: 'Genero was successfully created.' }
        format.json { render json: @genero, status: :created, location: @genero }
      else
        format.html { render action: "new" }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /generos/1
  # PUT /generos/1.json
  def update
    @genero = Genero.find(params[:id])

    respond_to do |format|
      if @genero.update_attributes(params[:genero])
        format.html { redirect_to @genero, notice: 'Genero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1
  # DELETE /generos/1.json
  def destroy
    @genero = Genero.find(params[:id])
    @genero.destroy

    respond_to do |format|
      format.html { redirect_to generos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/seriados_controller.rb
class SeriadosController < ApplicationController
  def index
    @seriados = Seriado.paginate(:page => params[:page], :per_page => 5).order("nome")
  end
  
  def new
    @seriado = Seriado.new
  end
  
  def create
    @seriado = Seriado.new(params[:seriado])
    
    if @seriado.save
      redirect_to seriados_url
    else
      render :action => :new
    end
  end
  
  def edit
    @seriado = Seriado.find(params[:id])
  end
  
  def update
    @seriado = Seriado.find(params[:id])
    
    if @seriado.update_attributes(params[:seriado])
      redirect_to seriados_url
    else
      render :action => :edit
    end
  end

  def destroy
    @seriado = Seriado.find(params[:id])
    @seriado.destroy
    redirect_to seriados_url
  end
  
  def buscar
    @termo = params[:termo]
    @seriados = Seriado.where("nome like '%#{@termo}%'").order("nome")
    render :action => :index
  end

end

app/controllers/temporadas_controller.rb
class TemporadasController < ApplicationController
  def index
    @seriado = Seriado.find(params[:seriado_id])
    @temporadas = @seriado.temporadas
  end
  
  def new
    @seriado = Seriado.find(params[:seriado_id])
    @temporada = Temporada.new(:seriado_id => @seriado.id)
  end
  
  def create
    @temporada = Temporada.new(params[:temporada])
    @seriado = Seriado.find(@temporada.seriado_id)
        
    if @temporada.save
      redirect_to seriado_temporadas_path(@seriado.id)
    else
      render :action => :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/seriados_helper.rb
module SeriadosHelper
end

app/views/generos/_form.html.erb
<%= form_for(@genero) do |f| %>
  <% if @genero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genero.errors.count, "error") %> prohibited this genero from being saved:</h2>

      <ul>
      <% @genero.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/generos/edit.html.erb
<h1>Editing genero</h1>

<%= render 'form' %>

<%= link_to 'Show', @genero %> |
<%= link_to 'Back', generos_path %>

app/views/generos/index.html.erb
<h1>Listing generos</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @generos.each do |genero| %>
  <tr>
    <td><%= genero.name %></td>
    <td><%= link_to 'Show', genero %></td>
    <td><%= link_to 'Edit', edit_genero_path(genero) %></td>
    <td><%= link_to 'Destroy', genero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Genero', new_genero_path %>

app/views/generos/new.html.erb
<h1>New genero</h1>

<%= render 'form' %>

<%= link_to 'Back', generos_path %>

app/views/generos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @genero.name %>
</p>


<%= link_to 'Edit', edit_genero_path(@genero) %> |
<%= link_to 'Back', generos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Episoder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/seriados/_form.html.erb
<%= form_for(@seriado, :html => { :multipart => true }) do |f| %> 
  <%= f.label :nome, "Nome" %>
  <%= f.text_field :nome %>  
  <%= f.file_field :foto %>
  <br/>
  <%= f.label :inicio, "Início" %>
  <%= date_select :seriado, :inicio, :start_year => 2000, :end_year => Time.now.year %>
  <br/>
  <%= f.label :status, "Status" %>
  <%= f.select(:status, [["Andamento", "A"], ["Cancelado", "C"]], {:prompt => 'Selecione um Status'}) %>
  <br/>
  <%= f.label :sinopse, "Sinopse" %>
  <%= f.text_area :sinopse, :rows => 5, :cols => 50 %>

  <br/>
  <%= f.submit text_button %>
<% end %>

app/views/seriados/edit.html.erb
<%= render 'form', :text_button => 'Atualizar' %>

app/views/seriados/index.html.erb
<b>Seriados</b>

<%= form_tag("buscar", :method => "get") do %>
  <%= label_tag(:termo, "Buscar por:") %>
  <%= text_field_tag(:termo) %>
  <%= submit_tag("Buscar") %>
<% end %>

<table>
	<% @seriados.each do |s| %>
	<tr>
		<td><%= link_to s.nome, edit_seriado_path(s) %></td>
		<td><%= image_tag s.foto.url(:thumb) %></td>
		<td><%= link_to 'T', seriado_temporadas_path(s.id) %>
		<td><%= link_to '✄', s, :action => :destroy, :confirm => 'Tem certeza?', :method => :delete %>
	</tr>
	<% end %>
</table>
<%= will_paginate @seriados, :previous_label => "<", :next_label => ">" %>

<%= link_to '+', new_seriado_path %>

app/views/seriados/new.html.erb
<%= render 'form', :text_button => 'Salvar' %>

app/views/temporadas/index.html.erb
<b>Temporadas</b>

<table>
	<% @temporadas.each do |t| %>
	<tr>
		<td><%= t.numero %></td>
	</tr>
	<% end %>
</table>

<%= link_to '+', new_seriado_temporada_path(@seriado.id) %>

app/views/temporadas/new.html.erb
<%= form_for([@seriado, @temporada]) do |f| %> 
  <%= f.label :numero, "Numero" %>
  <%= f.text_field :numero %>
  <br/>
  <%= f.label :sinopse, "Sinopse" %>
  <%= f.text_area :sinopse, :rows => 5, :cols => 50 %>

  <br/>
  <%= f.hidden_field :seriado_id, :value => @seriado.id %>
  <%= f.submit 'Salvar' %>
<% end %>